const quantity=document.getElementById("animoco-cart-quantity");
const chipInput=document.getElementById("family-chip");
const verifyButton=document.getElementById("verify-family-chip");
const familyStatus=document.getElementById("family-status");
let familyEligible=false,verifiedChipValue="";
function setFamilyStatus(kind,message){familyStatus.className=`family-status ${kind}`;familyStatus.textContent=message}
function clearFamilyEligibility(){familyEligible=false;verifiedChipValue="";setFamilyStatus("idle","Saisissez les 15 chiffres de la puce pour vérifier votre tarif.")}
chipInput.addEventListener("input",()=>{if(chipInput.value!==verifiedChipValue)clearFamilyEligibility()});
verifyButton.addEventListener("click",async()=>{verifyButton.disabled=true;verifyButton.textContent="Vérification…";setFamilyStatus("checking","Vérification en cours…");try{const response=await fetch("/api/family-eligibility",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chipNumber:chipInput.value})});const result=await response.json().catch(()=>({}));if(response.status===400&&result.error==="invalid_chip"){clearFamilyEligibility();setFamilyStatus("error","Format invalide : saisissez exactement les 15 chiffres de la puce.")}else if(!response.ok){clearFamilyEligibility();setFamilyStatus("error","Le service de vérification est momentanément indisponible. Vous pouvez commander au tarif public ou réessayer plus tard.")}else if(result.recognized===true){familyEligible=true;verifiedChipValue=chipInput.value;setFamilyStatus("success","Famille Dynastie reconnue : votre tarif de 17,99 € est appliqué.")}else{familyEligible=false;verifiedChipValue=chipInput.value;setFamilyStatus("not-recognized","Cette puce n’est pas reconnue dans le registre actuel. Le tarif public de 19,99 € s’applique. Contactez-nous si vous pensez qu’il s’agit d’une erreur.")}}catch{clearFamilyEligibility();setFamilyStatus("error","Le service de vérification est momentanément indisponible. Vous pouvez commander au tarif public ou réessayer plus tard.")}finally{verifyButton.disabled=false;verifyButton.textContent="Vérifier la puce"}});
const sharedCart=OrkhanCart.createCartStore();
document.getElementById("add-animoco").addEventListener("click",event=>{if(!quantity.reportValidity())return;const message=document.getElementById("animoco-cart-message");try{const line=OrkhanProductCart.animocoLine({quantity:quantity.value,chipNumber:chipInput.value,familyEligible:familyEligible&&chipInput.value===verifiedChipValue});OrkhanProductCart.addLine(sharedCart,line);OrkhanCart.updateCounters(document,sharedCart.count());OrkhanProductCart.showAddConfirmation(event.currentTarget,"Médaille Animoco ajoutée au panier.",message)}catch{message.textContent="Choisissez une quantité comprise entre 1 et 20.";message.classList.add("visible")}});
